proxy:
  image: littleqz/shadowsocks
  container_name: ss_proxy
  environment:
    - SERVER=<your-server>
    - SERVER_PORT=<port>
    - LOCAL_PORT=1080
    - PASSWORD=<your-password>
    - TIMEOUT=60
    - METHOD=aes-256-cfb
  expose:
    - "1080"
  ports:
    - "1080:1080"
